name: ImageStick
version: '${version}'
main: me.kall.imageStick.ImageStickPlugin
api-version: '1.21'
authors: [Kasualix]

depend: [ImageFrame]

commands:
  imagestick:
    description: ImageStick main command
    usage: /imagestick import <directory> <width> <height>
    permission: imagestick.use

permissions:
  imagestick.use:
    description: Allows use of imagestick commands
    default: op